Migrate docs [WIP]
openshift/backplane-cli pull request #23
Opened 2023-02-22 06:39 UTC by hectorakemp

### What type of PR is this?

_(bug/feature/cleanup/documentation)_

### What this PR does / Why we need it?

### Which Jira/Github issue(s) does this PR fix?

_Resolves #_

### Special notes for your reviewer

### Pre-checks (if applicable)

- [ ] Ran unit tests locally
- [ ] Validated the changes in a cluster
- [ ] Included documentation changes with PR

2023-02-23 01:41 UTC, wanghaoran1988 commented on README.md
> +The onboarding documentation can be found on [The Source Wiki](https://source.redhat.com/groups/public/openshiftplatformsre/wiki/backplane_user_documentation).
Let's remove this for now.

2023-02-23 01:42 UTC, wanghaoran1988 commented on README.md
> +the minimal version required is `go 1.16`. You can check this with `go version`
Should be go 1.18 ? https://github.com/openshift/backplane-cli/blob/main/go.mod#L3

2023-02-23 01:43 UTC, wanghaoran1988 commented on README.md
> +Then run `GOPRIVATE=github.com go install github.com/openshift/backplane-cli/cmd/ocm-backplane@{TAG_VERSION}`
Do we need GOPRIVATE for github?

2023-02-23 01:47 UTC, wanghaoran1988 commented on README.md
> +In this example, we will login to a cluster with id `123456abcdef` in production environment, and we have the OCM client environment setup [like this](https://github.com/openshift/ops-sop/blob/master
Let's use https://github.com/openshift-online/ocm-cli#log-in in stead of the private sop repo.

2023-02-23 01:49 UTC, wanghaoran1988 commented on README.md
> +### Monitoring UI Access
Let's remove this part, it's been deprecated.

2023-02-23 01:52 UTC, wanghaoran1988 commented on README.md
> +- Instructions on how to submit a new managed script is detailed [here](https://source.redhat.com/groups/public/openshiftplatformsre/wiki/backplane_scripts).
Let's remove this.

2023-02-23 01:52 UTC, wanghaoran1988 commented on README.md
> +## Feedback
Let's remove this for now?

2023-02-23 01:54 UTC, wanghaoran1988 commented on docs/PS1-setup.md
> +~~~
Let's remove this example? or update to not include the 'siwu' ?

2023-02-23 04:29 UTC, supreeth7 requested changes

2023-02-23 04:29 UTC, supreeth7 commented on README.md
> +  ```
We do not have `ocm-container` scripts for now, so this can be omitted.

2023-02-27 03:23 UTC, hectorakemp commented
/retest

2023-02-27 04:16 UTC, supreeth7 commented
/lgtm
/approve

2023-02-27 04:19 UTC, merged