Add config unit tests
openshift/backplane-cli pull request #296
Opened 2023-12-17 21:29 UTC by samanthajayasinghe

### What type of PR is this?
tests

2023-12-18 07:38 UTC, supreeth7 requested changes
Thanks for enhancing our test coverage.
Can you please update the PR description to be more descriptive for posterity?

2023-12-18 07:38 UTC, supreeth7 commented on pkg/cli/config/config_test.go
> +		config := BackplaneConfiguration{URL: "https://api-backplane.apps.openshiftapps.com", ProxyURL: nil}
Must've gotten in there by mistake, but as you already know we shouldn't be even hinting to the API URL which remotely resembles the actual API.

```suggestion
		config := BackplaneConfiguration{URL: "https://dummy-url", ProxyURL: nil}
```

2023-12-18 07:38 UTC, supreeth7 commented on pkg/cli/config/config_test.go
> +		proxyURL := "http://squid.myproxy.com"
```suggestion
		proxyURL := "http://dummy-proxy"
```

2023-12-18 21:23 UTC, samanthajayasinghe commented
Thanks, @supreeth7, for the review .. sorry for copy/pasting old tests and fixed the issue

2023-12-19 13:04 UTC, supreeth7 approved these changes
/lgtm

2023-12-19 13:08 UTC, merged