make the testjob source dir configurable
openshift/backplane-cli pull request #367
Opened 2024-03-12 08:15 UTC by bmeng

### What type of PR is this?

_feature_

### What this PR does / Why we need it?

Currently, we have the ocm backplane testjob command to test the script with custom image, but it has to be run under the script dir
Add the new parameter to specify the source dir for the script

### Which Jira/Github issue(s) does this PR fix?

_Resolves #_

### Special notes for your reviewer

### Pre-checks (if applicable)

- [x] Ran unit tests locally
- [x] Validated the changes in a cluster
- [ ] Included documentation changes with PR

2024-03-13 01:59 UTC, bmeng commented
/retest

2024-03-13 14:50 UTC, MitaliBhalla requested changes

2024-03-13 14:50 UTC, MitaliBhalla commented on cmd/ocm-backplane/testJob/createTestJob.go
> +		logger.Errorf("Error reading metadata yaml: %v, ensure either you are in a script directory or specified the corrent source dir", err)
```suggestion
		logger.Errorf("Error reading metadata yaml: %v, ensure either you are in a script directory or you have specified the correct source dir", err)
```

2024-03-22 05:29 UTC, hectorakemp reviewed
Great work @bmeng !
I think only one change is needed for an `lgtm` from me. We need a test for the negative case of when the specified source dir doesn't exist on the file system. Then it's `lgtm`!

2024-03-26 02:56 UTC, bmeng commented
@hectorakemp thanks for review.
Have added a new function `checkDirectory()` to ensure the given directory is valid. And related test added.

2024-03-26 05:45 UTC, hectorakemp approved these changes
/lgtm
/approve

2024-03-26 05:48 UTC, merged